### ISSUE TITLE
Gen install `ctpl`

### ISSUE THREAD

**Issue by EduardoAC** [EugenMayer/concourse-pipeline-templateer#2]
Currently, I installed this package after setup ruby `2.5.3`. However, the command printout a set of missing dependencies that are not found on ruby ecosystem. Can you help me with this problem?

```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'dwm' (>= 0) among 15 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/eduardoac/.gem/ruby/2.5.3:/Users/eduardoac/.rubies/ruby-2.5.3/lib/ruby/gems/2.5.0', execute `gem env` for more information
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1031:in `find_by_name'
	from /Users/eduardoac/.gem/ruby/2.5.3/gems/ctpl-0.0.6/bin/ctpl:7:in `<top (required)>'
	from /usr/local/bin/ctpl:22:in `load'
	from /usr/local/bin/ctpl:22:in `<main>'
```

**Comment by EugenMayer** [comment]
As with most thing right now, ruby 2.5 tends to break things. I have no real time to work on this, but feal free to patch it - i am happy to merge a PR :)

Or simply use ruby 2.4 - this is what i do, since i have a gazzlion things being broken with 2.5. From tiller, to docker-sync to diplomat, docker-compose ( gem )and much more.

**Comment by EduardoAC** [comment]
Thanks for your quick answer, I understand and I would love too but I have 0 knowledge on Ruby . 

Summary, I tried with `Ruby 2.3.7` and it didn't work either.

Perhaps you can tell me which is the version that I can use and more than happy to close the issue.

**Comment by EugenMayer** [comment]
i should have read your stacktrace .. i made a stupid copy&paste error in a from a different gem into the binstubs. 

I just released to 0.0.7 - please use that, it will work. Sorry

**Comment by EduardoAC** [comment]
Top, thanks for fixing it

**Comment by EugenMayer** [comment]
yw :)
